### ISSUE TITLE
Issue with JEB generation

### ISSUE THREAD

**Issue by danschultzer** [webhippie/po_to_json#4]
I don't understand [this part of the code](https://github.com/webhippie/po_to_json/blob/master/lib/po_to_json.rb#L171):

```ruby
  def build_trans
    buffer.each do |key, string|
      trans[$1.to_i] = string if key.to_s.match(/^msgstr_(\d+)/)
    end

    trans.unshift(detect_plural)
  end
```

Why is the plural put at the beginning, and not the end? I can't get anything to translate unless I change it to:

```ruby
    def build_trans
      buffer.each do |key, string|
        trans[$1.to_i] = string if key.to_s.match(/^msgstr_(\d+)/)
      end

      trans.push(detect_plural)
    end
```

**Comment by tboerger** [comment]
I'm pretty sure that this method is covered by tests. I will try to check that today when I'm at a computer.

**Comment by danschultzer** [comment]
All the tests are validating against [`[nil, TRANSLATION]`](https://github.com/webhippie/po_to_json/blob/master/spec/po_to_json_spec.rb#L48). It confuses me, it seems fully intended, while at the same time I can't get it to work with JED because the first argument is expected be the singular translation. Might be something I've overlooked.

**Comment by vilius** [comment]
@danschultzer you are right. Jed format was recently changed by this following commit: https://github.com/SlexAxton/Jed/commit/8cc37367d55eda9f800f3a4fa5fab6b5756e9ad7 - which is a breaking change for po_to_json and several other gems which depend on it (eg. gettext_i18n_rails_js)

**Comment by danschultzer** [comment]
@vilius: Ah, that makes sense, I get the issue with `gettext_i18n_rails_js`. I can do the PR for this gem, but since it's over multiple gems, I'll let you guys review it first.

**Comment by tboerger** [comment]
Feel free to create a pull request, else i will do it on monday.

**Comment by danschultzer** [comment]
I attempted to fix it, but ran into issues in the specs with `last author` and other values. I attempted to just remove the push completely if there was no plural version:

```ruby
  def build_trans
    buffer.each do |key, string|
      trans[$1.to_i] = string if key.to_s.match(/^msgstr_(\d+)/)
    end

    trans.push(detect_plural) unless detect_plural.nil?
    trans
  end
```

**Comment by tboerger** [comment]
Again i did not find the time today to come back to this. I hope i can fix that really soon as i need this gem packaged for a SUSE project as well :)

**Comment by tboerger** [comment]
I have fixed the issue and released 1.0.0 because of the backwards compat breakage. Thank you for your report and sorry for the delay, had a little bit stress the last days.

**Comment by vilius** [comment]
Fantastic! Thanks @tboerger

**Comment by tboerger** [comment]
An update for gettext_i18n_rails_js will follow soon :)

**Comment by danschultzer** [comment]
:+1:
